/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NodeJsSEAConfiguration {
  $schema?: string;
  /**
   * Path to the entry-point JavaScript file.
   */
  main: string;
  mainFormat?: "commonjs" | "module";
  /**
   * Path to the Node.js executable used as the base.
   */
  executable?: string;
  /**
   * Path to the generated executable or SEA blob.
   */
  output: string;
  disableExperimentalSEAWarning?: boolean;
  useSnapshot?: boolean;
  useCodeCache?: boolean;
  execArgv?: string[];
  execArgvExtension?: "none" | "env" | "cli";
  assets?: {
    [k: string]: string;
  };
}
